CC=icc
CFLAGS=-mkl -O3 -mmic -openmp -L /c1/apps/intel-cluster-studio/2013.0.028/composer_xe_2013.1.117/compiler/lib/mic -Wno-unknown-pragmas -std=c99 -vec-report3 	


all:
	${CC} ${CFLAGS} firstMatrix.c -o firstMatrix 


